/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.printer.swing;

import com.printer.Printers;
import com.printer.swing.ticket.TicketGraphic;
import com.printer.swing.ticket.TicketPrint;

import java.awt.Graphics;

/**
 *
 * @author ale
 */
public class TicketPanel extends javax.swing.JPanel {

    public TicketGraphic tg = new TicketGraphic();
    public TicketPrint ticketPrint = new TicketPrint(tg);
    
    /**
     * Creates new form TicketPanel
     */
    public TicketPanel() {
        initComponents();
        printButton.addActionListener(l -> Printers.print(ticketPrint));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        printButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fontLabel = new javax.swing.JLabel();
        boldLabel = new javax.swing.JLabel();
        rotateLabel = new javax.swing.JLabel();

        canvasPanel.setBorder(null);

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        printButton.setText("Print");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel1, gridBagConstraints);

        leftMarginSlide.setValue(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(leftMarginSlide, gridBagConstraints);

        rightMarginSlide.setValue(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(rightMarginSlide, gridBagConstraints);

        rightMarginLabel.setText("Right Margin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(rightMarginLabel, gridBagConstraints);

        paperSizeLabel.setText("Paper Width (dpi)");
        paperSizeLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(paperSizeLabel, gridBagConstraints);

        paperSizeSlide.setMaximum(300);
        paperSizeSlide.setValue(164);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(paperSizeSlide, gridBagConstraints);

        leftMarginLabel.setText("Left Margin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(leftMarginLabel, gridBagConstraints);

        leftPaddingLabel.setText("Left Padding");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(leftPaddingLabel, gridBagConstraints);

        leftPaddingSlide.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(leftPaddingSlide, gridBagConstraints);

        topMarginLabel.setText("Top Margin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(topMarginLabel, gridBagConstraints);

        topMarginSlider.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(topMarginSlider, gridBagConstraints);

        lineSpacingLabel.setText("Space Between Lines");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(lineSpacingLabel, gridBagConstraints);

        lineSpacingSlide.setPaintLabels(true);
        lineSpacingSlide.setPaintTicks(true);
        lineSpacingSlide.setValue(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(lineSpacingSlide, gridBagConstraints);

        lineSpacingValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel2.add(lineSpacingValueLabel, gridBagConstraints);

        paperSizeValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel2.add(paperSizeValueLabel, gridBagConstraints);

        topMarginValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(topMarginValueLabel, gridBagConstraints);

        leftPaddingValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(leftPaddingValueLabel, gridBagConstraints);

        leftMarginValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(leftMarginValueLabel, gridBagConstraints);

        rightMarginValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(rightMarginValueLabel, gridBagConstraints);

        fontLabel.setText("Fuente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(fontLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(fontComboBox, gridBagConstraints);

        boldLabel.setText("Negrita");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(boldLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(boldCheckBox, gridBagConstraints);

        fontSizeLabel.setText("Tamaño");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(fontSizeLabel, gridBagConstraints);

        fontSizeSlider.setMaximum(32);
        fontSizeSlider.setMinimum(1);
        fontSizeSlider.setValue(9);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(fontSizeSlider, gridBagConstraints);

        rotateLabel.setText("Rotar (grados)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(rotateLabel, gridBagConstraints);

        rotateSlider.setMaximum(180);
        rotateSlider.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(rotateSlider, gridBagConstraints);

        rotateValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        jPanel2.add(rotateValueLabel, gridBagConstraints);

        fontSizeValueLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        jPanel2.add(fontSizeValueLabel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(printButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JCheckBox boldCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JLabel boldLabel;
    public final javax.swing.JPanel canvasPanel = new javax.swing.JPanel();
    public final javax.swing.JComboBox<String> fontComboBox = new javax.swing.JComboBox<>();
    private javax.swing.JLabel fontLabel;
    private final javax.swing.JLabel fontSizeLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider fontSizeSlider = new javax.swing.JSlider();
    public final javax.swing.JLabel fontSizeValueLabel = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public final javax.swing.JLabel leftMarginLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider leftMarginSlide = new javax.swing.JSlider();
    public final javax.swing.JLabel leftMarginValueLabel = new javax.swing.JLabel();
    public final javax.swing.JLabel leftPaddingLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider leftPaddingSlide = new javax.swing.JSlider();
    public final javax.swing.JLabel leftPaddingValueLabel = new javax.swing.JLabel();
    public final javax.swing.JLabel lineSpacingLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider lineSpacingSlide = new javax.swing.JSlider();
    public final javax.swing.JLabel lineSpacingValueLabel = new javax.swing.JLabel();
    public final javax.swing.JLabel paperSizeLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider paperSizeSlide = new javax.swing.JSlider();
    public final javax.swing.JLabel paperSizeValueLabel = new javax.swing.JLabel();
    private javax.swing.JButton printButton;
    public final javax.swing.JLabel rightMarginLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider rightMarginSlide = new javax.swing.JSlider();
    public final javax.swing.JLabel rightMarginValueLabel = new javax.swing.JLabel();
    private javax.swing.JLabel rotateLabel;
    public final javax.swing.JSlider rotateSlider = new javax.swing.JSlider();
    public final javax.swing.JLabel rotateValueLabel = new javax.swing.JLabel();
    public final javax.swing.JLabel topMarginLabel = new javax.swing.JLabel();
    public final javax.swing.JSlider topMarginSlider = new javax.swing.JSlider();
    public final javax.swing.JLabel topMarginValueLabel = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(final Graphics g) {
      super.paint(g);
      tg.redraw(g, canvasPanel);
    }

}
