## Spring Boot configuration
#spring:
#  profiles:
#    active: google
## Spring Security configuration
#security:
#  oauth2:
#    client:
#      clientId: 668302098281-8megaf2nvssl0e8f9mhvgcr867bao1ti.apps.googleusercontent.com
#      clientSecret: 1j8gARu-6djTPAwEH4ruPR9Y
#      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#      clientAuthenticationScheme: form
#      scope:
#        - openid
#        - email
#        - profile
#    resource:
#      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#      preferTokenInfo: true
## Server configuration
#server:
# port: 8181

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 668302098281-8megaf2nvssl0e8f9mhvgcr867bao1ti.apps.googleusercontent.com
            client-secret: 1j8gARu-6djTPAwEH4ruPR9Y